### ISSUE TITLE
config中有不懂的配置

### ISSUE THREAD

**Issue by leo95123** [chariothy/dnspod-ddns#2]
请问一下config中
'server_token': 'token_to_request_ddns_server_api'      # 请求DDSN server api的token
'server_port': 7788                                     # DDNS server 端口
这两个配置是什么？

**Comment by chariothy** [comment]
这个是用在你跑一个ddns server的时候用的，
server_port 是这个服务的端口
server_token 是这个服务的token，防止别人盗用，你自己约定生成一个

举例：
https://your.domain.com:server_port/ip?domain=sub.your.domain.com&token=token_to_request_ddns_server_api

**Comment by leo95123** [comment]
谢谢回复！

**Comment by leo95123** [comment]
> 谢谢回复！

我自己另外用Node写了一个，虽然不完善，但是自己用够了。
